import turtle

turtle.ht()
turtle.down()

# message = "NNEESOOEES"
message = "NNEESOOESEENNEEOOSEOSEEENNESENSSENNEESSOOEEENNEEOOSEOSEEENEENOOEESOOSEEEEEEENONSESENNSSENNEESSOOEEENNSSEENNSSEEENOONEEOOSEESEEEENNEESSOOEEENNEESOOEESENNESENSSEEENOONEEOOSEESEEEENNSSEEENNEESOOEESEEEENNEEOOSEOSEEENNEESSOOEEENNEESOOESEENNEEOOSEOSEEEENNOEEOSSEEEEENNEESOOEESOOEEENNEESOOESEENNSSEENNSSENNESNESSENNEEOOSEOSEEENNSSEENNSSEEENOONEEOOSEESENNEEOOSEOSEEEEEENNEESSOOEEENNEEOOSEOSEEENNESNESSENNEESOOEESENNSSENNESENSS"

turtle.setworldcoordinates(-1, -1, 2000, 2000)

x=0
y=0

for char in message:
	if char == "N":
		y += 10
	if char == "S":
		y -= 10
	if char == "E":
		x += 10
	if char == "O":
		x -= 10

	turtle.goto(x, y)

x += 100
turtle.goto(x, y)
